spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASS}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    use-root-path: true
  paths-to-match:
    - /auth/**
    - /api/**/v1/**